CREATE TABLE pcg_reference (
  id    varchar(10) PRIMARY KEY,
  name  text NOT NULL
);

CREATE INDEX idx_pcg_reference_name ON pcg_reference (name);

INSERT INTO pcg_reference (id, name) VALUES
  ('1', 'Comptes de Financement Permanent'),
  ('11', 'Capitaux Propres'),
  ('1111', 'Capital Social'),
  ('1112', 'Fonds de Dotation'),
  ('1117', 'Capital Personnel'),
  ('11171', 'Capital Individuel'),
  ('11175', 'Compte de l''Exploitant'),
  ('1119', 'Actionnaires, Capital souscrit non appelé'),
  ('112', 'Primes d’émission, de fusion et d''apport'),
  ('1121', 'Primes d''émission'),
  ('1122', 'Primes de Fusion'),
  ('1123', 'Primes d''apport'),
  ('113', 'Ecarts de réévaluation'),
  ('1130', 'Ecarts de réévaluation'),
  ('114', 'Réserve légale'),
  ('1140', 'Réserve légale'),
  ('115', 'Autres réserves'),
  ('1151', 'Réserves statutaires ou contractuelles'),
  ('1152', 'Réserves facultatives'),
  ('1155', 'Réserves réglementaires'),
  ('116', 'Report à nouveau'),
  ('1161', 'Report à nouveau (solde créditeur)'),
  ('1169', 'Report à nouveau (solde débiteur)'),
  ('118', 'Résultat net en Instance d''Affectation'),
  ('1181', 'Résultat net en Instance d''Affectation (Solde Créditeur)'),
  ('1189', 'Résultat net en Instance d''Affectation (Solde débiteur)'),
  ('119', 'Résultat net de l''exercice'),
  ('1191', 'Résultat net de l''exercice (Solde créditeur)'),
  ('1199', 'Résultat net de l''exercice (Solde débiteur)'),
  ('13', 'Capitaux Propres et Assimilés'),
  ('131', 'Subventions d''investissement'),
  ('1311', 'Subvention d''investissement reçus'),
  ('1319', 'Subvention d''investissement inscrits au compte de produit et charges'),
  ('135', 'Provisions réglementées'),
  ('1351', 'Provisions pour amortissements dérogatoires'),
  ('1352', 'Provisions pour plus-values en instance d''imposition'),
  ('1354', 'Provisions Pour Investissements'),
  ('1355', 'Provisions pour reconstitution des gisements'),
  ('1356', 'Provisions pour acquisition et construction de logements'),
  ('1358', 'Autres provisions réglementées'),
  ('14', 'Dettes de Financement'),
  ('141', 'Emprunts Obligataires'),
  ('1410', 'Emprunts Obligataires'),
  ('148', 'Autres dettes de Financement'),
  ('1481', 'Emprunts auprès des établissements de crédits'),
  ('1482', 'Avance de l''Etat'),
  ('1483', 'Dettes rattachées à des participations'),
  ('1484', 'Billets de Fonds'),
  ('1485', 'Avances reçus et comptes courants bloqués'),
  ('1486', 'Fournisseurs d''immobilisations'),
  ('1487', 'Dépôts et cautionnements reçus'),
  ('1488', 'Dettes de Financement diverses'),
  ('15', 'Provisions Durables Pour Risques et Charges'),
  ('151', 'Provisions pour Risques'),
  ('1511', 'Provisions pour litiges'),
  ('1512', 'Provisions pour garanties données aux clients'),
  ('1513', 'Provisions pour propre assureur'),
  ('1514', 'Provisions pour pertes sur marché à terme'),
  ('1515', 'Provisions pour amendes, doubles droits, pénalités'),
  ('1516', 'Provisions pour pertes de change'),
  ('1518', 'Autres provisions pour risque'),
  ('155', 'Provisions pour charges'),
  ('1551', 'Provisions Pour impôts'),
  ('1552', 'Provisions, pensions de retraite et obligations similaires'),
  ('1555', 'Provisions pour charges à répartir sur plusieurs exercices'),
  ('1558', 'Autres provisions pour charges'),
  ('16', 'Comptes de liaison des établissements et succursales'),
  ('160', 'Comptes de liaison des établissements et succursales'),
  ('1601', 'Comptes de liaison de sièges'),
  ('1605', 'Comptes de liaison des établissements'),
  ('17', 'Ecarts de conversion - Passif'),
  ('171', 'Augmentation des créances immobilisées'),
  ('1710', 'Augmentation des créances immobilisées'),
  ('172', 'Diminution des dettes de Financement'),
  ('1720', 'Diminution des dettes de Financement'),
  ('2', 'Comptes d''Actif Immobilisé'),
  ('21', 'Immobilisation en non-valeurs'),
  ('211', 'Frais Préliminaires'),
  ('2111', 'Frais de Constitution'),
  ('2112', 'Frais préalables au démarrage'),
  ('2113', 'Frais d''augmentation du capital'),
  ('2114', 'Frais sur opérations de Fusion, scissions et transformations'),
  ('2116', 'Frais de prospection'),
  ('2117', 'Frais de publicité'),
  ('2118', 'Autres frais préliminaires'),
  ('212', 'Charges à répartir sur plusieurs exercices'),
  ('2121', 'Frais d''acquisition des immobilisations'),
  ('2125', 'Frais d''émission des emprunts'),
  ('2128', 'Autres charges à répartir'),
  ('213', 'Primes de remboursement des obligations'),
  ('2130', 'Primes de remboursement des obligations'),
  ('22', 'Immobilisation Incorporelles'),
  ('221', 'Immobilisations en recherche et Développement'),
  ('2210', 'Immobilisations en recherche et Développement'),
  ('222', 'Brevets, marques, droits et valeurs similaires'),
  ('2220', 'Brevets, marques, droits et valeurs similaires'),
  ('223', 'Fonds Commercial'),
  ('2230', 'Fonds Commercial'),
  ('228', 'Autres immobilisations Incorporelles'),
  ('2285', 'Autres immobilisations Incorporelles'),
  ('23', 'Immobilisations Corporelles'),
  ('231', 'Terrains'),
  ('2311', 'Terrains nus'),
  ('2312', 'Terrains aménagés'),
  ('2313', 'Terrains bâtis'),
  ('2314', 'Terrains de gisement'),
  ('2316', 'Agencement et aménagements de terrains'),
  ('2318', 'Autres terrains'),
  ('232', 'Construction'),
  ('2321', 'Bâtiments'),
  ('23211', 'Bâtiments industriels (A, B...)'),
  ('23214', 'Bâtiments administratifs et commerciaux (A, B…)'),
  ('23218', 'Autres bâtiments'),
  ('2323', 'Construction sur terrains d''autrui'),
  ('2325', 'Ouvrages d''infrastructures'),
  ('2327', 'Agencement et aménagements des constructions'),
  ('2328', 'Autres constructions'),
  ('233', 'Installations Techniques, matériel et outillage'),
  ('2331', 'Installations Techniques'),
  ('2332', 'Matériel et outillage'),
  ('23321', 'Matériel'),
  ('23324', 'Outillage'),
  ('2333', 'Emballages récupérables identifiables'),
  ('2338', 'Autres Installations techniques, matériel et outillage'),
  ('234', 'Matériel de transport'),
  ('2340', 'Matériel de transport'),
  ('235', 'Mobilier, matériel de bureau et aménagements divers'),
  ('2351', 'Mobilier de bureau'),
  ('2352', 'Matériel de bureau'),
  ('2355', 'Matériel Informatique'),
  ('2356', 'Agencement, installations et aménagements divers (de biens n''appartenant pas à l''entreprise)'),
  ('2358', 'Autres mobiliers, matériel de bureau et aménagements divers'),
  ('238', 'Autres immobilisations corporelles'),
  ('2380', 'Autres immobilisations corporelles'),
  ('239', 'Immobilisations corporelles en cours'),
  ('2392', 'immobilisations Corporelles en cours et terrains de constructions'),
  ('2393', 'immobilisations Corporelles en cours et terrains des installations techniques, matériel et outillage'),
  ('2394', 'Immobilisations corporelles en cours de matériel de transports'),
  ('2395', 'Immobilisations corporelles en cours de mobilier, matériel de bureau et aménagement divers'),
  ('2397', 'Avances et acomptes versés sur commandes d''immobilisations corporelles'),
  ('2398', 'Autres immobilisations corporelles en cours'),
  ('24', 'Immobilisations Financières'),
  ('25', 'Immobilisations Financières'),
  ('241', 'Prêts immobilisés'),
  ('2411', 'Prêts au personnel'),
  ('2415', 'Prêts aux associés'),
  ('2416', 'Billets de Fonds'),
  ('2418', 'Autres prêts'),
  ('248', 'Autres créances financières'),
  ('2481', 'Titres immobilisés (Droits de créance)'),
  ('24811', 'Obligations'),
  ('24813', 'Bons d''équipements'),
  ('24818', 'Bons divers'),
  ('2483', 'Créances rattachées à des participations'),
  ('2486', 'Dépôts et cautionnements versés'),
  ('24861', 'Dépôts'),
  ('24864', 'Cautionnements'),
  ('2487', 'Créances Immobilisées'),
  ('2488', 'Créances financières diverses'),
  ('251', 'Titres de participation'),
  ('2510', 'Titres de participation'),
  ('258', 'Autres titres immobilisés (Titres de propriété)'),
  ('2581', 'Actions'),
  ('2588', 'Titres divers'),
  ('27', 'Ecarts de conversion Actif'),
  ('271', 'Diminution des créances Immobilisées'),
  ('2710', 'Diminution des créances Immobilisées'),
  ('272', 'Augmentation des dettes de financement'),
  ('2720', 'Augmentation des dettes de financement'),
  ('28', 'Amortissements des immobilisations'),
  ('281', 'Amortissements des en non-valeurs'),
  ('2811', 'Amortissements des frais préliminaires'),
  ('28111', 'Amortissements des Faris de constitution'),
  ('28112', 'Amortissement des frais préliminaires au démarrage'),
  ('28113', 'Amortissements des frais d''augmentation de capital'),
  ('28114', 'Amortissements des frais sur opérations des fusions scissions et transformations'),
  ('28116', 'Amortissements des frais d prospection'),
  ('28117', 'Amortissements des frais de publicité'),
  ('28118', 'Amortissements des autres frais préliminaires'),
  ('2812', 'Amortissements des charges à répartir'),
  ('28121', 'Amortissements des frais d''acquisition des immobilisations'),
  ('28125', 'Amortissements des frais d''émission des emprunts'),
  ('28128', 'Amortissements des autres charges à répartir'),
  ('28813', 'Amortissements, primes de remboursement des obligations'),
  ('282', 'Amortissements des immobilisations incorporelles'),
  ('2821', 'Amortissement de l''immobilisation en recherche et développement'),
  ('2822', 'Amortissement des brevets, marques, droits et valeurs similaires'),
  ('2823', 'Amortissement du fond commercial'),
  ('2828', 'Amortissement des autres immobilisations incorporelles'),
  ('283', 'Amortissements des immobilisations corporelles'),
  ('2831', 'Amortissement des terrains'),
  ('28311', 'Amortissement des terrains nus'),
  ('28312', 'Amortissement des terrains aménagés'),
  ('28313', 'Amortissement des terrains bâtis'),
  ('28314', 'Amortissement des  terrains de gisement'),
  ('28316', 'Amortissement des agencements et aménagements des terrains'),
  ('28318', 'Amortissement des autres terrains'),
  ('2832', 'Amortissement des autres construction'),
  ('28321', 'Amortissement des bâtiments'),
  ('28323', 'Amortissement des construction sur terrains d''autrui'),
  ('28325', 'Amortissement des ouvrages d''infrastructure'),
  ('28327', 'Amortissement des installations, agencements et aménagements des constructions'),
  ('28328', 'Amortissement des autres constructions'),
  ('2833', 'Amortissement des Installations techniques, matériels et outillage'),
  ('28331', 'Amortissement des installations techniques'),
  ('28332', 'Amortissement du matériel et outillage'),
  ('28333', 'Amortissement des emballages récupérables identifiables'),
  ('28338', 'Amortissement des autres installations techniques'),
  ('2834', 'Amortissement du matériel de transport'),
  ('2835', 'Amortissement du mobilier, matériel de bureau'),
  ('28351', 'Amortissement du mobilier de bureau'),
  ('28352', 'Amortissement du matériel de bureau'),
  ('28355', 'Amortissement du matériel informatique'),
  ('28356', 'Amortissement des agencements, installations et aménagements divers'),
  ('28358', 'Amortissement des autres mobilier, matériel de bureau et aménagements divers'),
  ('2838', 'Amortissement des autres immobilisations corporelles'),
  ('29', 'Provisions pour dépréciation des immobilisations'),
  ('292', 'Provisions pour dépréciation des immobilisations incorporelles'),
  ('2920', 'Provisions pour dépréciation des immobilisations incorporelles'),
  ('293', 'Provisions pour dépréciation des immobilisations corporelles'),
  ('2930', 'Provisions pour dépréciation des immobilisations corporelles'),
  ('294', 'Provisions pour dépréciation des immobilisations financières'),
  ('295', 'Provisions pour dépréciation des immobilisations financières'),
  ('2941', 'Provisions pour dépréciation des prêts immobilisés'),
  ('2948', 'Provisions pour dépréciation des autres créances financières'),
  ('2951', 'Provisions pour dépréciation des titres de participations'),
  ('2958', 'Provisions pour dépréciation des autres immobilisés'),
  ('3', 'Comptes d''actif Circulation (Hors Trésorerie)'),
  ('31', 'Stocks'),
  ('311', 'Marchandises'),
  ('3111', 'Marchandises (Groupe A)'),
  ('3112', 'Marchandises (Groupe B)'),
  ('3116', 'Marchandises en cours de route'),
  ('3118', 'Autres marchandises'),
  ('312', 'Matières et fournitures consommables'),
  ('3121', 'Matières premières'),
  ('31211', 'Matières premières (Groupe A)'),
  ('31212', 'Matières premières (Groupe B)'),
  ('3122', 'Matières et fournitures consommables'),
  ('31221', 'Matières consommables (Groupe A)'),
  ('31222', 'Matières consommables (Groupe B)'),
  ('31223', 'Combustibles'),
  ('31224', 'Produits d''entretien'),
  ('31225', 'Fournitures d''atelier et d''usine'),
  ('31226', 'Fournitures de magasin'),
  ('31227', 'Fournitures de Bureau'),
  ('3123', 'Emballages'),
  ('31231', 'Emballages Perdus'),
  ('31232', 'Emballages récupérables non identifiables'),
  ('31233', 'Emballages à usage mixte'),
  ('3126', 'Matières et fournitures consommables en cours de route'),
  ('3128', 'Autres matières et fournitures consommables'),
  ('313', 'Produits en cours'),
  ('3131', 'Biens en cours'),
  ('31311', 'Biens produits en cours'),
  ('31312', 'Biens Intermédiaires en cours'),
  ('31317', 'Biens résiduels en cours'),
  ('3134', 'Services en cours'),
  ('31341', 'Travaux en cours'),
  ('31342', 'Etudes en cours'),
  ('31343', 'Prestations en cours'),
  ('3138', 'Autres produits en cours'),
  ('314', 'Produits intermédiaires et produits résiduels'),
  ('3141', 'Produits intermédiaires'),
  ('31411', 'Produits intermédiaires (Groupe A)'),
  ('31412', 'Produits intermédiaires (Groupe B)'),
  ('3145', 'Produits résiduels (ou matières de récupération)'),
  ('31451', 'Déchets'),
  ('31452', 'Rebuts'),
  ('31453', 'Matières de récupération'),
  ('3148', 'Autres produits intermédiaires et produits résiduels'),
  ('315', 'Produits Finis'),
  ('3151', 'Produits Finis (groupe A)'),
  ('3152', 'Produits Finis (groupe B)'),
  ('3156', 'Produits finis en cours de route'),
  ('3158', 'Autres produits finis'),
  ('34', 'Créances de l''actif circulant'),
  ('341', 'Fournisseurs débiteur, avances et acomptes'),
  ('3411', 'Fournisseurs - avances et acomptes versés sur commandes d''exploitation'),
  ('3413', 'Fournisseurs - créances pour emballages et matériels à rendre'),
  ('3417', 'Rabais, remises et ristournes à obtenir - avoirs non encoure reçus'),
  ('3418', 'Autres fournisseurs débiteurs'),
  ('342', 'Clients et comptes rattachés'),
  ('3421', 'Clients'),
  ('34211', 'Clients (Groupe A)'),
  ('34212', 'Clients (Groupe B)'),
  ('3423', 'Clients - retenues de garanties'),
  ('3424', 'Clients douteux ou litigieux'),
  ('3425', 'Clients - effets à recevoir'),
  ('3427', 'Clients - factures à établir et créances sur travaux non encore facturables'),
  ('34271', 'Clients - factures à établir'),
  ('34272', 'Créances sur travaux non encore facturables'),
  ('3428', 'Autres clients et comptes rattachés'),
  ('343', 'Personnel - débiteur'),
  ('3431', 'Avances et acomptes au personnel'),
  ('3438', 'Personnel - autres débiteurs'),
  ('345', 'Etat - débiteur'),
  ('3451', 'Subventions à recevoir'),
  ('34511', 'Subventions d''investissements à recevoir'),
  ('34512', 'subventions d''exploitation à recevoir'),
  ('34513', 'Subventions d''équilibre à recevoir'),
  ('3453', 'Acomptes sur impôts sur les résultats'),
  ('3455', 'Etat - TVA récupérable'),
  ('34551', 'Etat - TVA récupérable sur Immobilisations'),
  ('34552', 'Etat - TVA récupérable sur charges'),
  ('3456', 'Etat - crédit de TVA (suivant déclarations)'),
  ('3458', 'Etat - autres comptes débiteurs'),
  ('346', 'Comptes d''associés - débiteurs'),
  ('3461', 'Associés - comptes d''apport en société'),
  ('3462', 'Actionnaires - capital souscrit et appelé non versé'),
  ('3463', 'Comptes courants des associés - débiteurs'),
  ('3464', 'Associés - opérations faites en commun'),
  ('3467', 'Créances rattachées aux comptes d''associés'),
  ('3468', 'Autres comptes d''associés - débiteurs'),
  ('348', 'Autres débiteurs'),
  ('3481', 'Créances sur cession d''immobilisations'),
  ('3482', 'Créances sur cession d''éléments d''actif circulant'),
  ('3487', 'Créances rattachées aux autres débiteurs'),
  ('3488', 'Divers débiteurs'),
  ('349', 'Comptes de régularisation'),
  ('3491', 'Charges constatées d''avance'),
  ('3493', 'Intérêts courus et non échus à percevoir'),
  ('3495', 'Comptes de participations périodique des charges'),
  ('3497', 'Comptes transitoires ou d''attente - débiteurs'),
  ('35', 'Titres te valeurs de placement'),
  ('350', 'Titres te valeurs de placement'),
  ('3501', 'Actions, partie libérée'),
  ('3502', 'Actions, partie non libérée'),
  ('3504', 'Obligations'),
  ('3506', 'Bons de caisse et bons de trésor'),
  ('35061', 'Bons de caisse'),
  ('35062', 'Bons de trésor'),
  ('3508', 'Autres titres et valeurs de placement similaires'),
  ('37', 'Ecarts de conversion-actif (éléments circulants)'),
  ('370', 'Ecarts de conversion-actif (éléments circulants)'),
  ('3701', 'Diminution des créances circulantes'),
  ('3702', 'Diminution des dettes circulantes'),
  ('39', 'Provision pour dépréciation des comptes de l''actif circulant'),
  ('391', 'Provisions pour dépréciation des stocks'),
  ('3911', 'Provisions pour dépréciation des Marchandises'),
  ('3912', 'Provisions pour dépréciation des matières et fournitures'),
  ('3913', 'Provisions pour dépréciation des produits en cours'),
  ('3914', 'Provisions pour dépréciation des produits intermédiaires'),
  ('3915', 'Provisions pour dépréciation des produits finis'),
  ('394', 'Provisions pour dépréciation des créances de l''actif circulant'),
  ('3941', 'Provisions pour dépréciation - fournisseurs débiteurs, avances et acomptes'),
  ('3942', 'Provisions pour dépréciation des clients et comptes rattachés'),
  ('3943', 'Provisions pour dépréciation du personnel - débiteur'),
  ('3946', 'Provisions pour dépréciation des comptes d''associés débiteurs'),
  ('3948', 'Provisions pour dépréciation des autres débiteurs'),
  ('395', 'Provisions pour dépréciation des titres et valeur de placement'),
  ('3950', 'Provisions pour dépréciation des titres et valeur de placement'),
  ('4', 'Comptes de passif circulant (Hors trésorerie)'),
  ('44', 'Dettes du passif circulant'),
  ('441', 'Fournisseurs et comptes rattachés'),
  ('4411', 'Fournisseurs'),
  ('44111', 'Fournisseurs - catégorie A'),
  ('44112', 'Fournisseurs - catégorie B'),
  ('4413', 'Fournisseurs - retenues de garantie'),
  ('4415', 'Fournisseurs - effets à payer'),
  ('4417', 'Fournisseurs - factures non parvenues'),
  ('4418', 'Autres fournisseurs et comptes rattachés'),
  ('442', 'Clients créditeurs, avances et acomptes'),
  ('4421', 'Clients - avances et acomptes reçus sur commandes en cours'),
  ('4425', 'Clients - dettes pour emballages et matériel consignés'),
  ('4427', 'Rabais, remises et ristournes à accorder - avoirs à établir'),
  ('4428', 'Autres clients créditeurs'),
  ('443', 'Personnel - créditeur'),
  ('4432', 'Rémunérations dues au personnel'),
  ('4433', 'Dépôts du personnel créditeurs'),
  ('4434', 'Oppositions sur salaires'),
  ('4437', 'Charges de personnel à payer'),
  ('4438', 'Personnel - autres créditeurs'),
  ('444', 'Organismes sociaux'),
  ('4441', 'Caisse nationale de la sécurité sociale'),
  ('4443', 'Caisses de retraite'),
  ('4445', 'Mutuelles'),
  ('4447', 'charges sociales à payer'),
  ('4448', 'Autres organismes sociaux'),
  ('445', 'Etat - créditeur'),
  ('4452', 'Etat, impôts, taxes et assimilés'),
  ('44521', 'Etat, taxe urbaine et taxe d''édilité'),
  ('44522', 'Etat, patente'),
  ('44525', 'Etat, PTS et PSN'),
  ('4453', 'Etat, impôts sur les résultats'),
  ('4455', 'Etat, TVA facturée'),
  ('4456', 'Etat, TVA due (suivant déclarations)'),
  ('4457', 'Etat, impôts et taxes à payer'),
  ('4458', 'Etat, autres comptes créditeurs'),
  ('446', 'Comptes d''associés - créditeurs'),
  ('4461', 'Associés - capital à rembourser'),
  ('4462', 'Associés - versements reçus sur augmentation de capital'),
  ('4463', 'Comptes courants des associés - créditeurs'),
  ('4464', 'Associés - opérations faites en commun'),
  ('4465', 'Associés - dividendes à payer'),
  ('4468', 'Autres comptes d''associés créditeurs'),
  ('448', 'Autres créanciers'),
  ('4481', 'Dettes sur acquisition des immobilisations'),
  ('4483', 'Dettes sur acquisition des titres et valeurs de placement'),
  ('4484', 'Obligations échus à rembourser'),
  ('4485', 'Obligations, coupons à payer'),
  ('4487', 'Dettes rattachées aux autres créanciers'),
  ('4488', 'Divers créanciers'),
  ('449', 'Comptes de régularisation - passif'),
  ('4491', 'Produits constatés d''avance'),
  ('4493', 'Intérêts courus et non échus à payer'),
  ('4495', 'Comptes de répartition périodique des produits'),
  ('4497', 'Comptes transitoires ou d''attente - créditeurs'),
  ('45', 'Autres provisions pour risques et charges'),
  ('450', 'Autres provisions pour risque et charges'),
  ('4501', 'Provisions pour litiges'),
  ('4502', 'Provisions pour garanties données aux clients'),
  ('4505', 'Provisions pour amendes, doubles droits et pénalités'),
  ('4506', 'Provisions pour pertes de change'),
  ('4507', 'Provisions pour impôts'),
  ('4508', 'Autres provisions pour risque et charges'),
  ('47', 'Ecarts de conversion - Passif'),
  ('470', 'Ecarts de conversion - Passif (éléments circulants)'),
  ('4701', 'Augmentation des créances circulantes'),
  ('4702', 'Diminution des dettes circulantes'),
  ('5', 'Comptes de trésorerie'),
  ('51', 'Trésorerie - actif'),
  ('511', 'Chèques et valeurs à encaisser'),
  ('5111', 'Chèques à encaisser ou à l''encaissement'),
  ('51111', 'Chèques en portefeuille'),
  ('51112', 'Chèques à l''encaissement'),
  ('5113', 'Effets à encaisser ou à l''encaissement'),
  ('51131', 'Effets échus à encaisser'),
  ('51132', 'Effets à l''encaissement'),
  ('5115', 'Virements de fonds'),
  ('5118', 'Autres valeurs à encaisser'),
  ('514', 'Banques, Trésorerie Générale et Chèques Postaux débiteurs'),
  ('5141', 'Banques (soldes débiteurs)'),
  ('5143', 'Trésorerie Générale'),
  ('5146', 'Chèques postaux'),
  ('5148', 'Autres établissements financiers et assimilés (soldes débiteurs)'),
  ('516', 'Caisses, régies d''avances et accréditifs'),
  ('5161', 'Caisses'),
  ('51611', 'Caisse Centrale'),
  ('51613', 'Caisse (Succursale ou agence A)'),
  ('51614', 'Caisse (Succursale ou agence B)'),
  ('5165', 'Régies d''avances et accréditifs'),
  ('55', 'Trésorerie - Passif'),
  ('552', 'Crédits d''escompte'),
  ('5520', 'Crédits d''escompte'),
  ('553', 'Crédits de trésorerie'),
  ('5530', 'Crédits de trésorerie'),
  ('554', 'Banques (soldes créditeurs)'),
  ('5541', 'Banques (soldes créditeurs)'),
  ('5548', 'Autres établissements financiers et assimilés (soldes créditeurs)'),
  ('59', 'Provisions pour dépréciation des comptes de trésorerie'),
  ('590', 'Provisions pour dépréciation des comptes de trésorerie'),
  ('5900', 'Provisions pour dépréciation des comptes de trésorerie'),
  ('6', 'Charges'),
  ('61', 'Charges d''exploitation'),
  ('611', 'Achats revendus de marchandises'),
  ('6111', 'Achats de marchandises (Groupe A)'),
  ('6112', 'Achats de marchandises (Groupe B)'),
  ('6114', 'Variation des stocks de marchandises'),
  ('6118', 'Achats revendus de marchandises des exercices antérieurs'),
  ('6119', 'Rabais, remises, et ristournes obtenus sur achats de marchandises'),
  ('612', 'Achats consommés de matières et fournitures'),
  ('6121', 'Achats de matières premières'),
  ('61211', 'Achats de matières premières A'),
  ('61212', 'Achats de matières premières B'),
  ('6122', 'Achats de matières et fournitures consommables'),
  ('61221', 'Achats de matières et fournitures A'),
  ('61222', 'Achats de matières et fournitures B'),
  ('61223', 'Achats de combustibles'),
  ('61224', 'Achats de produits d''entretien'),
  ('61225', 'Achats de fournitures d''atelier d''usine'),
  ('61226', 'Achats de fournitures de magasin'),
  ('61227', 'Achats de fournitures de bureau'),
  ('6123', 'Achats d''emballages'),
  ('61231', 'Achats d''emballages perdus'),
  ('61232', 'Achats d''emballages récupérables non identifiables'),
  ('61233', 'Achats d''emballages à usage mixte'),
  ('6124', 'Variation des stocks de matières et fournitures'),
  ('61241', 'Variation des stocks de matières premières'),
  ('61242', 'Variation des stocks de matières et fournitures consommables'),
  ('61243', 'Variation des stocks d''emballages'),
  ('6125', 'Achats non stockés de matières et fournitures'),
  ('61251', 'Achats de fournitures non stockables'),
  ('61252', 'Achats de fournitures d''entretien'),
  ('61253', 'Achats de petit outillage et de petit équipement'),
  ('61254', 'Achats de fournitures de bureau'),
  ('6126', 'Achats de travaux, études et prestations de services'),
  ('61261', 'Achats de travaux'),
  ('61262', 'Achats d''études'),
  ('61263', 'Achats des prestations de service'),
  ('6128', 'Achats des matières et des fournitures des exercices antérieurs'),
  ('6129', 'Rabais, remises, et ristournes obtenus sur achats consommés de matières et fournitures'),
  ('61291', 'Rabais, remises, et ristournes obtenus sur achats de matières premières'),
  ('61292', 'Rabais, remises, et ristournes obtenus sur achats de matières et fournitures consommables'),
  ('61293', 'Rabais, remises, et ristournes obtenus sur achats d''emballages'),
  ('61295', 'Rabais, remises, et ristournes obtenus sur achats non stockés'),
  ('61296', 'Rabais, remises, et ristournes obtenus sur achats de travaux, études et prestations de services'),
  ('61298', 'Rabais, remises, et ristournes obtenus sur achats de matières et fournitures des exercices antérieurs'),
  ('613', 'Autres charges externes'),
  ('614', 'Autres charges externes'),
  ('6131', 'Locations et charges locatives'),
  ('61311', 'Location de terrains'),
  ('61312', 'Location de constructions'),
  ('61313', 'Location de matériel et d''outillage'),
  ('61314', 'Location de matériel et matériel de bureau'),
  ('61315', 'Location de matériel informatique'),
  ('61316', 'Location de matériel de transport'),
  ('61317', 'Malis sur emballages rendus'),
  ('61318', 'Location et charges locatives diverses'),
  ('6132', 'Redevances de crédit bail'),
  ('61321', 'Redevances de crédit bail, mobilier et matériel'),
  ('6133', 'Entretien et réparations'),
  ('61331', 'Entretien et réparations des biens immobiliers'),
  ('61332', 'Entretien et réparations des biens mobiliers'),
  ('61335', 'Maintenance'),
  ('6134', 'Primes d''assurance'),
  ('61341', 'Assurances multirisques (vol, incendie, responsabilité civile, etc.)'),
  ('61343', 'Assurances - Risques d''exploitation'),
  ('61345', 'Assurances - Matériel de transport'),
  ('61348', 'Autres assurances'),
  ('6135', 'Rémunérations du personnel extérieurs à l''entreprise'),
  ('61351', 'Rémunérations du personnel occasionnel'),
  ('61352', 'Rémunérations du personnel intérimaire'),
  ('61353', 'Rémunérations du personnel détaché ou prêté à l''entreprise'),
  ('6136', 'Rémunérations d''intermédiaires et honoraires'),
  ('61361', 'Commissions et courtages'),
  ('61365', 'honoraires'),
  ('61367', 'Frais d''actes et de contentieux'),
  ('6137', 'Redevances pour brevets, marques, droits et valeurs similaires'),
  ('61371', 'Redevances pour brevets'),
  ('61378', 'Autres redevances'),
  ('6141', 'Etudes, recherches et documentation'),
  ('61411', 'Etudes générales'),
  ('61413', 'Recherches'),
  ('61415', 'Documentation générale'),
  ('61416', 'Documentation technique'),
  ('6142', 'Transport'),
  ('61421', 'Transport du personnel'),
  ('61425', 'Transport sur achats'),
  ('61426', 'Transport sur ventes'),
  ('61428', 'Autres transports'),
  ('6143', 'Déplacements, missions et réceptions'),
  ('61431', 'Voyages et déplacements'),
  ('61433', 'Frais de déménagement'),
  ('61435', 'Missions'),
  ('61436', 'Réceptions'),
  ('6144', 'Publicité, publications et relations publiques'),
  ('61441', 'Annonces et insertions'),
  ('61442', 'Echantillons, catalogues et imprimés publicitaires'),
  ('61443', 'Foires et expositions'),
  ('61444', 'Primes de publicité'),
  ('61446', 'Publications'),
  ('61447', 'Cadeaux à la clientèle'),
  ('61448', 'Autres charges de publicité et relations publiques'),
  ('6145', 'Frais postaux et frais de télécommunications'),
  ('61451', 'Frais postaux'),
  ('61455', 'Frais de téléphone'),
  ('61456', 'Frais de télex et de télégrammes'),
  ('6146', 'Cotisations et dons'),
  ('61461', 'Cotisations'),
  ('61462', 'Dons'),
  ('6147', 'Services bancaires'),
  ('61471', 'Frais d''achat et de vente des titres'),
  ('61472', 'Frais sur effet de commerce'),
  ('61473', 'Frais et commissions sur services bancaires'),
  ('6148', 'Autres charges externes des exercices antérieurs'),
  ('6149', 'Rabais, remises et ristournes obtenus sur autres charges externes'),
  ('616', 'Impôts et taxes'),
  ('6161', 'Impôts et taxes directs'),
  ('61611', 'Taxe urbaine et taxe d''édilité'),
  ('61612', 'Patente'),
  ('61615', 'Taxes locales'),
  ('6165', 'Impôts et taxes indirects'),
  ('6167', 'Impôts, taxes et droits assimilés'),
  ('61671', 'Droits d''enregistrement et timbre'),
  ('61673', 'Taxes sur les véhicules'),
  ('61678', 'Autres impôts, taxes et droits assimilés'),
  ('6168', 'Impôts et taxes des exercices antérieurs'),
  ('617', 'Charges de personnel'),
  ('6171', 'Rémunération du personnel'),
  ('61711', 'Appointements et salaires'),
  ('61712', 'Primes et gratifications'),
  ('61713', 'Indemnités et avantages divers'),
  ('61714', 'Commissions au personnel'),
  ('61715', 'Rémunération des administrateurs, gérants et associés'),
  ('6174', 'charges sociales'),
  ('61741', 'Cotisations de sécurité sociale'),
  ('61742', 'Cotisations aux caisses de retraite'),
  ('61743', 'Cotisations aux mutuelles'),
  ('61744', 'Prestations familiales'),
  ('61745', 'Assurances accidents de travail'),
  ('6176', 'Charges sociales diverses'),
  ('61761', 'Assurances groupe'),
  ('61762', 'Prestations de retraites'),
  ('61763', 'Allocations aux œuvres sociales'),
  ('61764', 'Habillement et vêtements de travail'),
  ('61765', 'Indemnités de préavis et de licenciement'),
  ('61766', 'Médecine du travail, pharmacie'),
  ('61768', 'Autres charges sociales diverses'),
  ('6177', 'Rémunération de l''exploitant'),
  ('61771', 'Appointements et salaires'),
  ('61774', 'Charges sociales sur appointements et salaires de l''exploitant'),
  ('6178', 'Charges de personnel des exercices antérieurs'),
  ('618', 'Autres charges d''exploitation'),
  ('6181', 'Jetons de présence'),
  ('6182', 'Pertes sur créances irrécouvrables'),
  ('6185', 'Pertes sur opérations faites en commun'),
  ('6186', 'Transferts de profits sur opérations faites en commun'),
  ('6188', 'Autres charges d''exploitation des exercices antérieurs'),
  ('619', 'Dotation d''exploitation'),
  ('6191', 'Dotations d''exploitation aux amortissements de l''immobilisation en non-valeurs'),
  ('61911', 'Dotations d''exploitation aux amortissements des frais préliminaires'),
  ('61912', 'Dotations d''exploitation aux amortissements des charges à répartir'),
  ('6192', 'Dotations d''exploitation aux amortissements de l''immobilisation incorporelles'),
  ('61921', 'Dotations d''exploitation aux amortissements de l''immobilisation en recherche et développement'),
  ('61922', 'Dotations d''exploitation aux amortissements des brevets, marques, droits et valeurs similaires'),
  ('61923', 'Dotations d''exploitation aux amortissements du fonds commercial'),
  ('61928', 'Dotations d''exploitation aux amortissements des autres immobilisations incorporelles'),
  ('6193', 'Dotations d''exploitation aux amortissements des immobilisations corporelles'),
  ('61931', 'Dotations d''exploitation aux amortissements des terrains'),
  ('61932', 'Dotations d''exploitation aux amortissements des constructions'),
  ('61933', 'Dotations d''exploitation aux amortissements des installations techniques, matériel et outillage'),
  ('61934', 'Dotations d''exploitation aux amortissements du matériel de transport'),
  ('61935', 'Dotations d''exploitation aux amortissements des mobilier, matériel de bureau et aménagement divers'),
  ('61938', 'Dotations d''exploitation aux amortissements des autres immobilisations corporelles'),
  ('6194', 'Dotations d''exploitation aux provisions pour dépréciation des immobilisations'),
  ('61942', 'Dotations d''exploitation aux provisions pour dépréciation des immobilisations incorporelles'),
  ('61943', 'Dotations d''exploitation aux provisions pour dépréciation des immobilisations corporelles'),
  ('6195', 'Dotations d''exploitation aux provisions pour risques et charges'),
  ('61955', 'Dotations d''exploitation aux provisions pour risques et charges durables'),
  ('61957', 'Dotations d''exploitation aux provisions pour risques et charges momentanés'),
  ('6196', 'Dotations d''exploitation aux provisions pour dépréciation de l''actif circulant'),
  ('61961', 'Dotations d''exploitation aux provisions pour dépréciation des stocks'),
  ('61964', 'Dotations d''exploitation aux provisions pour dépréciation des créances de l''actif circulant'),
  ('6198', 'Dotations d''exploitation des exercices antérieurs'),
  ('61981', 'Dotations d''exploitation aux amortissements des exercices antérieurs'),
  ('61984', 'Dotations d''exploitation aux provisions des exercices antérieurs'),
  ('63', 'Charges financières'),
  ('631', 'Charges d''intérêt'),
  ('6311', 'Intérêts des emprunts et dettes'),
  ('63111', 'Intérêts des emprunts'),
  ('63113', 'Intérêts des dettes rattachées à des participations'),
  ('63114', 'Intérêts des comptes courants et dépôts créditeurs'),
  ('63115', 'Intérêts bancaires et sur opérations de financement'),
  ('63118', 'Autres intérêts des emprunts et dettes'),
  ('6318', 'Charges d''intérêt des exercices antérieurs'),
  ('633', 'Pertes de change'),
  ('6331', 'Pertes de change propres à l''exercice'),
  ('6338', 'Pertes de change des exercices antérieurs'),
  ('638', 'Autres charges financières'),
  ('6382', 'Pertes sur créances liées à des participations'),
  ('6385', 'Charges nettes sur cessions de titres et valeurs de placement'),
  ('6386', 'Escomptes accordés'),
  ('6388', 'Autres charges financières des exercices antérieurs'),
  ('639', 'Dotations financières'),
  ('6391', 'Dotations aux amortissements des primes de remboursement des obligations'),
  ('6392', 'Dotations aux provisions pour dépréciation des immobilisations financières'),
  ('6393', 'Dotations aux provisions pour risques et charges financières'),
  ('6394', 'Dotations aux provisions pour dépréciation des titres et valeurs de placement'),
  ('6396', 'Dotations aux provisions pour dépréciation des comptes de trésorerie'),
  ('6398', 'Dotations financières des exercices antérieurs'),
  ('65', 'Charges non courantes'),
  ('651', 'Valeurs nettes d''amortissements des immobilisations cédées'),
  ('6512', 'Valeurs nettes d''amortissement des immobilisations incorporelles cédées'),
  ('6513', 'Valeurs nettes d''amortissement des immobilisations corporelles cédées'),
  ('6514', 'Valeurs nettes d''amortissement des immobilisations financières cédées'),
  ('6518', 'Valeurs nettes d''amortissement des immobilisations cédées des exercices antérieurs'),
  ('656', 'Subventions accordées'),
  ('6561', 'Subventions accordées de l''exercice'),
  ('6568', 'Subventions accordées des exercices antérieurs'),
  ('658', 'Autres charges non courantes'),
  ('6581', 'Pénalités sur marchés et dédits'),
  ('65811', 'Pénalités sur marchés'),
  ('65812', 'Dédits'),
  ('6582', 'Rappels d''impôts (autres qu''impôts sur les résultats)'),
  ('6583', 'Pénalités et amendes fiscales ou pénales'),
  ('65831', 'Pénalités et amendes fiscales ou pénales'),
  ('65833', 'Pénalités et amendes pénales'),
  ('6585', 'Créances devenues irrécouvrables'),
  ('6586', 'Dons, libéralités et lots'),
  ('65861', 'Dons'),
  ('65862', 'Libéralités'),
  ('65863', 'Lots'),
  ('6588', 'Autres charges non courantes des exercices antérieurs'),
  ('659', 'Dotations pour courantes'),
  ('6591', 'Dotations aux amortissements exceptionnels des immobilisations'),
  ('65911', 'Dotations aux amortissements exceptionnels de l''immobilisation en non valeurs'),
  ('65912', 'Dotations aux amortissements exceptionnels des immobilisations incorporelles'),
  ('65913', 'Dotations aux amortissements exceptionnels des immobilisations corporelles'),
  ('6594', 'Dotations non courantes aux provisions réglementées'),
  ('65941', 'Dotations non courantes aux amortissements dérogatoires'),
  ('65942', 'Dotations non courantes pour plus-values en instance d''imposition'),
  ('65944', 'Dotations non courantes pour investissements'),
  ('65945', 'Dotations non courantes pour reconstitution de gisements'),
  ('65946', 'Dotations non courantes pour acquisition et construction de logement'),
  ('6595', 'Dotations non courantes aux provisions pour risques et charges'),
  ('65955', 'Dotations non courantes aux provisions pour risques et charges durables'),
  ('65957', 'Dotations non courantes aux provisions pour risques et charges momentanés'),
  ('6596', 'Dotations non courantes aux provisions pour dépréciation'),
  ('65962', 'Dotations non courantes aux provisions pour dépréciation de l''actif immobilisé'),
  ('65963', 'Dotations non courantes aux provisions pour dépréciation de l''actif circulant'),
  ('6598', 'Dotations non courantes des exercices antérieurs'),
  ('67', 'Impôts sur le résultats'),
  ('670', 'Impôts sur le résultats'),
  ('6701', 'Impôts sur les bénéfices'),
  ('6705', 'Imposition minimale annuelle des sociétés'),
  ('6708', 'Rappels et dégrèvements des impôts sur les résultats'),
  ('7', 'Comptes de produits'),
  ('71', 'Produits d''exploitation'),
  ('711', 'Ventes de marchandises'),
  ('7111', 'Ventes de marchandises au Maroc'),
  ('7113', 'Ventes de marchandises à l''étranger'),
  ('7118', 'Ventes de marchandises des exercices antérieurs'),
  ('7119', 'Rabais, remises et ristournes accordés par l''entreprise'),
  ('712', 'Ventes de biens et services produits'),
  ('7121', 'Ventes de biens et services produits au Maroc'),
  ('71211', 'Ventes de produits finis'),
  ('71212', 'Ventes de produits intermédiaires'),
  ('71217', 'Ventes de produits résiduels'),
  ('7122', 'Ventes de biens produits à l''étranger'),
  ('71221', 'Ventes de produits finis'),
  ('71222', 'Ventes de produits intermédiaires'),
  ('7124', 'Ventes de services produits au Maroc'),
  ('71241', 'Travaux'),
  ('71242', 'Etudes'),
  ('71243', 'Prestations de services'),
  ('7125', 'Ventes de services produits à l''étranger'),
  ('71251', 'Travaux'),
  ('71252', 'Etudes'),
  ('71253', 'Prestations de services'),
  ('7126', 'Redevances pour brevets, marques, droits et valeurs similaires'),
  ('7127', 'Ventes de produits accessoires'),
  ('71271', 'Locations diverses reçues'),
  ('71272', 'Commissions et courtages reçus'),
  ('71273', 'Produits de services exploités dans l''intérêt du personnel'),
  ('71275', 'Bonis sur reprises d''emballages consignés'),
  ('71276', 'Ports et frais accessoires'),
  ('71278', 'Autres ventes de produits accessoires'),
  ('7128', 'Ventes de biens set services produits des exercices antérieurs'),
  ('7129', 'Rabais, remises et ristournes accordés par l''entreprise'),
  ('71291', 'Rabais, remises et ristournes accordés sur ventes au Maroc des biens produits'),
  ('71292', 'Rabais, remises et ristournes accordés sur ventes à l''étranger des biens produits'),
  ('71294', 'Rabais, remises et ristournes accordés sur ventes au Maroc des services produits'),
  ('71295', 'Rabais, remises et ristournes accordés sur ventes à l''étranger des services produits'),
  ('71298', 'Rabais, remises et ristournes accordés sur ventes des biens et services produits des exercices antérieurs'),
  ('713', 'Variations des stocks des produits'),
  ('7131', 'Variations des stocks des produits en cours'),
  ('71311', 'Variations des stocks de biens produits en cours'),
  ('71312', 'Variations des stocks de produits intermédiaires en cours'),
  ('71317', 'Variations des stocks de produits résiduels en cours'),
  ('7132', 'Variations des stocks de biens produits'),
  ('71321', 'Variations des stocks de produits finis'),
  ('71322', 'Variations des stocks de produits intermédiaires'),
  ('71327', 'Variations des stocks de produits résiduels'),
  ('7134', 'Variations des stocks de services en cours'),
  ('71341', 'Variations des stocks de travaux'),
  ('71342', 'Variations des stocks d''études en cours'),
  ('71343', 'Variations des stocks de prestations en cours'),
  ('714', 'Immobilisations produits par l''entreprise pour elle-même'),
  ('7141', 'Immobilisations en non-valeurs produites'),
  ('7142', 'Immobilisations incorporelles produites'),
  ('7143', 'Immobilisations corporelles produites'),
  ('7148', 'Immobilisations produites des exercices antérieurs'),
  ('716', 'Subventions d''exploitation'),
  ('7161', 'Subventions d''exploitation reçues de l''exercice'),
  ('7168', 'Subventions d''exploitation reçues des exercices antérieurs'),
  ('718', 'Autres produits d''exploitation'),
  ('7181', 'Jetons de présence reçus'),
  ('7182', 'Revenus des immeubles non affectées à l''exploitation'),
  ('7185', 'Profits sur opérations faites en commun'),
  ('7186', 'Transferts de profits sur opérations faites en commun'),
  ('7188', 'Autres produits d''exploitation des exercices antérieurs'),
  ('719', 'Reprises d''exploitation ; Transfert de change'),
  ('7191', 'Reprises sur amortissements de l''immobilisation en non-valeur'),
  ('7192', 'Reprises sur amortissements des immobilisations incorporelles'),
  ('7193', 'Reprises sur amortissements des immobilisations corporelles'),
  ('7194', 'Reprises sur provisions pour dépréciation des immobilisations'),
  ('7195', 'Reprises sur provisions pour risques et charges'),
  ('7196', 'Reprises sur provisions pour dépréciation de l''actif circulant'),
  ('7197', 'Transfert de charges d''exploitation'),
  ('71971', 'Transfert de charges d''exploitation - achats de marchandises'),
  ('71972', 'Transfert de charges d''exploitation - achats consommés de matières et fournitures'),
  ('71973', 'Transfert de charges d''exploitation - autres charges externes'),
  ('71975', 'Transfert de charges d''exploitation - impôts et taxes'),
  ('71976', 'Transfert de charges d''exploitation - charges de personnel'),
  ('71978', 'Transfert de charges d''exploitation - autres charges d''exploitation'),
  ('7198', 'Reprises sur amortissements et provisions des exercices antérieurs'),
  ('71981', 'Reprises sur amortissements des exercices antérieurs'),
  ('71984', 'Reprises sur Provisions des exercices antérieurs'),
  ('73', 'Produits financiers'),
  ('732', 'Produits des titres de participation et des autres titres immobilisés'),
  ('7321', 'Revenus des titres de participation'),
  ('7325', 'Revenus des titres immobilisés'),
  ('7328', 'Produits des titres de participation et des autres titres immobilisés des exercices antérieurs'),
  ('733', 'Gains de change'),
  ('7331', 'Gains de change propres à l''exercice'),
  ('7338', 'Gains de change des exercices antérieurs'),
  ('738', 'Intérêts et autres produits financiers'),
  ('7381', 'Intérêts et produits assimilés'),
  ('73811', 'Intérêts des prêts'),
  ('73813', 'Revenus des autres créances financières'),
  ('7383', 'Revenus des créances rattachées à des participations'),
  ('7384', 'Revenus des titres et valeurs de placement'),
  ('7385', 'Produits nets sur cessions de titres et valeurs de placement'),
  ('7386', 'Escomptes obtenus'),
  ('7388', 'Intérêts et autres produits financiers des exercices antérieurs'),
  ('739', 'Reprises financières ; Transfert de change'),
  ('7391', 'Reprises sur amortissement des primes de remboursement des obligations'),
  ('7392', 'Reprises sur provisions pour dépréciation des immobilisations financières'),
  ('7393', 'Reprises sur provisions pour risques et charges financières'),
  ('7394', 'Reprises sur provisions pour dépréciation des titres et valeurs de placement'),
  ('7396', 'Reprises sur provisions pour dépréciation des comptes de trésorerie'),
  ('7397', 'Transfert de charges financières'),
  ('73971', 'Transferts - charges d''intérêts'),
  ('73973', 'Transferts - pertes de change'),
  ('73978', 'Transferts - autres charges financières'),
  ('7398', 'Reprises sur dotations financières des exercices antérieurs'),
  ('75', 'Produits non courants'),
  ('751', 'Produits des cessions des immobilisations'),
  ('7512', 'Produits des cessions des immobilisations incorporelles'),
  ('7513', 'Produits des cessions des immobilisations corporelles'),
  ('7514', 'Produits des cessions des immobilisations financières (droits de propriété)'),
  ('7518', 'Produits des cessions des immobilisations des exercices antérieurs'),
  ('756', 'Subventions d''équilibre'),
  ('7561', 'Subventions d''équilibre reçues de l''exercice'),
  ('7568', 'Subventions d''équilibre reçues des exercices antérieurs'),
  ('757', 'Reprises sur subventions d''investissement'),
  ('7577', 'Reprises sur subventions d''investissement de l''exercice'),
  ('7578', 'Reprises sur subventions d''investissement des exercices antérieurs'),
  ('758', 'Autres produits non courants'),
  ('7581', 'Pénalités et dédits reçus'),
  ('75811', 'Pénalités reçus sur marché'),
  ('75812', 'Dédits reçus'),
  ('7582', 'Dégrèvements d''impôts (autres qu''impôts sur résultat)'),
  ('7585', 'Rentrées sur créances soldées'),
  ('7586', 'Dons, libéralités et lots reçus'),
  ('75861', 'Dons'),
  ('75862', 'Libéralités'),
  ('75863', 'Lots'),
  ('7588', 'Autres produits non courants des exercices antérieurs'),
  ('759', 'Reprises non courantes ; Transfert de change'),
  ('7591', 'Reprises non courantes sur amortissements exceptionnelles des immobilisations'),
  ('75911', 'Reprises non courantes sur amortissements exceptionnelles des immobilisations en non-valeurs'),
  ('75912', 'Reprises non courantes sur amortissements exceptionnelles des immobilisations incorporelles'),
  ('75913', 'Reprises non courantes sur amortissements exceptionnelles des immobilisations corporelles'),
  ('7594', 'Reprises non courantes sur provisions réglementées'),
  ('75941', 'Reprises sur amortissements dérogatoires'),
  ('75942', 'Reprises sur plus values en instance d''imposition'),
  ('75944', 'Reprises sur provisions pour investissements'),
  ('75945', 'Reprises sur provisions pour reconstitution de gisements'),
  ('75946', 'Reprises sur provisions pour acquisition et construction de logements'),
  ('7595', 'Reprises non courantes sur provisions pour risques et charges'),
  ('75955', 'Reprises non courantes sur provisions pour risques et charges durables'),
  ('75957', 'Reprises non courantes sur provisions pour risques et charges momentanés'),
  ('7596', 'Reprises non courantes sur provisions pour dépréciation'),
  ('75962', 'Reprises non courantes sur provisions pour dépréciation de l''actif immobilisé'),
  ('75963', 'Reprises non courantes sur provisions pour dépréciation de l''actif circulant'),
  ('7597', 'Transfert de charges non courantes'),
  ('7598', 'Reprises non courantes des exercices antérieurs'),
  ('8', 'Comptes de résultats'),
  ('81', 'Résultat s''exploitation'),
  ('810', 'Résultat s''exploitation'),
  ('811', 'Marge brute'),
  ('814', 'Valeur ajoutée'),
  ('817', 'Excédent brut s''exploitation'),
  ('8171', 'Excédent brut s''exploitation (créditeur)'),
  ('8179', 'Insuffusance brute d''exploitation (débiteur)'),
  ('83', 'Résultat financier'),
  ('84', 'Résultat courant'),
  ('85', 'Résultat non courant'),
  ('86', 'Résultat avant impôt'),
  ('88', 'Résultat après impôt'),
  ('9', 'Comptes analytiques'),
  ('90', 'Comptes de produits et charges réfléchis'),
  ('903', 'Stocks et provisions pour dépréciation de stocks réfléchis'),
  ('9031', 'Stocks réfléchis'),
  ('9039', 'Provisions pour dépréciation de stocks réfléchis'),
  ('906', 'Charges réfléchies'),
  ('9061', 'Charges d''exploitation réfléchies'),
  ('9063', 'Charges financières réfléchies'),
  ('9065', 'Charges non courantes réfléchies'),
  ('9067', 'Impots sur les résultats réfléchis'),
  ('907', 'Produits réfléchis'),
  ('9071', 'Produits d''exploitation réfléchis'),
  ('9073', 'Produits financiers réfléchis'),
  ('9075', 'Produits non courants réfléchis'),
  ('908', 'Résultats réfléchis'),
  ('9081', 'Résultat d''exploitation réfléchi'),
  ('9083', 'Résultat financier réfléchis'),
  ('9084', 'Résultat courant réfléchis'),
  ('9085', 'Résultat non courant réfléchi'),
  ('9086', 'Résultat avant impôt réfléchi'),
  ('9088', 'Résultat après impots réfléchi'),
  ('91', 'Comptes de reclassement et d''analyse (ouverts et attribués selon les nécéssité de l''entreprise)'),
  ('92', 'Sections Analytiques'),
  ('921', 'Sections générales'),
  ('9211', 'Section A'),
  ('9212', 'Section B'),
  ('923', 'Sections d''approvisionnement'),
  ('9231', 'Section A'),
  ('9232', 'Section B'),
  ('925', 'Sections de production'),
  ('9251', 'Section A'),
  ('9252', 'Section B'),
  ('927', 'Sections de distribution'),
  ('9271', 'Section A'),
  ('9272', 'Section B'),
  ('928', 'Autres sections analytiques'),
  ('9281', 'Section A'),
  ('9282', 'Section B'),
  ('93', 'Couts d''achat ou de production'),
  ('933', 'Couts d''achat'),
  ('9331', 'Couts d''achat de marchandises'),
  ('9335', 'Couts d''achat de matières et de fournitures'),
  ('935', 'Couts de production'),
  ('9351', 'Couts de production des produits (Groupe A)'),
  ('9352', 'Couts de production des produits (Groupe B)'),
  ('938', 'Autres couts d''achat ou de production'),
  ('9381', 'Couts de production des immobilisations'),
  ('94', 'Inventaire permanent des stocks'),
  ('941', 'Inventaire permanent des marchandises'),
  ('9411', 'Marchandises (Groupe A)'),
  ('9412', 'Marchandises (Groupe B)'),
  ('9416', 'Marchandises en cours de route'),
  ('9418', 'Autres marchandises'),
  ('942', 'Inventaire permanent des matières et fournitures consommables'),
  ('9421', 'Matières premières'),
  ('9422', 'Matières et fournitures consommables'),
  ('9423', 'Emballages'),
  ('9426', 'Matières et fournitures consommables en cours de route'),
  ('9428', 'Autres matières et fournitures consommables'),
  ('943', 'Inventaire permanent des produits en cours'),
  ('9431', 'Biens en cours'),
  ('9434', 'Services en cours'),
  ('9438', 'Autres produits en cours'),
  ('944', 'Inventaire permanent des produits intérmédiaires et produits résiduels'),
  ('9441', 'Produits intérmédiaires'),
  ('9445', 'Produits résiduels'),
  ('9448', 'Autres produits intermédiaires et produits résiduels'),
  ('945', 'Inventaire permanent des produits finis'),
  ('9451', 'Produits finis (Groupe A)'),
  ('9452', 'Produits finis (Groupe B)'),
  ('9456', 'Produits finis en cours de route'),
  ('9458', 'Autres produits finis'),
  ('949', 'Provisions pour dépréciation de stocks'),
  ('9491', 'Provisions pour dépréciation des Marchandises'),
  ('9492', 'Provisions pour dépréciation des matières et fournitures consommables'),
  ('9493', 'Provisions pour dépréciation des produits en cours'),
  ('9494', 'Provisions pour dépréciation des produits intermédiaires et produits résiduels'),
  ('9495', 'Provisions pour dépréciation des produits finis'),
  ('95', 'Couts de revient'),
  ('953', 'Couts de revient des marchandises'),
  ('9531', 'couts de revient des marchandises (Groupe A)'),
  ('9532', 'Couts de revient des marchandises (Groupe B)'),
  ('955', 'Couts de revient des produits'),
  ('9551', 'Couts de revient des produits (Groupe A)'),
  ('9552', 'Couts de revient des produits (Groupe B)'),
  ('958', 'Autres couts de revient'),
  ('9581', 'Couts de revient (Groupe A)'),
  ('9582', 'Couts de revient (Groupe B)'),
  ('96', 'Ecarts sur couts de revient préétablis'),
  ('962', 'Ecarts sur sections'),
  ('9621', 'Ecarts sur quantités'),
  ('9622', 'Ecarts sur couts'),
  ('964', 'Ecarts sur inventaires permanent des stocks'),
  ('9641', 'Ecarts sur quantités'),
  ('9642', 'Ecarts sur couts'),
  ('97', 'Différence d''incorporation'),
  ('971', 'Charges non incorporables'),
  ('972', 'Charges supplétives incorporées'),
  ('973', 'Produits non incorporés'),
  ('974', 'Différences sur charges incorporables'),
  ('975', 'Différences sur produits incorporables'),
  ('976', 'Différences d''inventaire'),
  ('9761', 'Différences d''inventaire sur marchandises'),
  ('9762', 'Différences d''inventaire sur matières et fournitures consommables'),
  ('9763', 'Différences d''inventaire sur produits en cours'),
  ('9764', 'Différences d''inventaire sur produits intérmediaires et produits résiduels'),
  ('9765', 'Différences d''inventaire sur produits finis'),
  ('977', 'Différences sur niveau d''activité'),
  ('978', 'Autres différences d''incorporation'),
  ('98', 'Résultats analytiques'),
  ('981', 'Résultats analytiques sur marchandises'),
  ('9811', 'Résultats analytiques sur marchandises (Groupe A)'),
  ('9812', 'Résultats analytiques sur marchandises (Groupe B)'),
  ('982', 'Résultats analytiques sur biens produits'),
  ('9821', 'Résultats analytiques sur biens produits (Groupe A)'),
  ('9822', 'Résultats analytiques sur biens produits (Groupe A)'),
  ('983', 'Résultats analytiques sur services produits'),
  ('9831', 'Résultats analytiques sur services produits (Groupe A)'),
  ('9832', 'Résultats analytiques sur services produits (Groupe B)'),
  ('986', 'Report des écarts sur couts préétablis'),
  ('987', 'Report des différences d''incorporation'),
  ('99', 'Comptes de laisons internes'),
  ('991', 'Liaisons internes propres à un même établissement'),
  ('995', 'Cessions à d''autres établissement'),
  ('9951', 'Cessions fournies à d''autres établissements'),
  ('9955', 'Cessions reçues d''autres établissements'),
  ('0', 'Comptes spéciaux'),
  ('01', 'Bilan d''ouverture'),
  ('011', 'Réoverture des comptes de financement permanent'),
  ('0111', 'Réouverture des comptes de capitaux propres'),
  ('01111', 'Réouverture des comptes de capital social ou permanent'),
  ('01112', 'Réouverture des comptes des primes d''émission, de fusion, d''apport'),
  ('01113', 'Réouverture des comptes des écarts de réévaluation'),
  ('01114', 'Réouverture des comptes de résérve légale'),
  ('01115', 'Réouverture des comptes des autres réserves'),
  ('01116', 'Réouverture des comptes du report à nouveau'),
  ('01118', 'Réouverture des comptes des résultats nets en instance d''affectation'),
  ('01119', 'Réouverture des comptes du résultat net de l''exercice'),
  ('0113', 'Réouverture des comptes de capitaux propres assimilés'),
  ('01131', 'Réouverture des comptes de subventions d''investissement'),
  ('01135', 'Réouverture des comptes de provisions réglementées'),
  ('0114', 'Réouverture des comptes des dettes de financement'),
  ('01141', 'Réouverture des comptes d''emprunts obligataires'),
  ('01148', 'Réouverture des comptes des autres dettes de financeemnt'),
  ('0115', 'Réouverture des comptes de provisions durables pour risques et charges'),
  ('01151', 'Réouverture des comptes de provisiosn pour risques'),
  ('01155', 'Réouverture des comptes de provisiosn pour charges'),
  ('0116', 'Réouverture des comptes de liaison des établissements et succursales'),
  ('0117', 'Réouverture des comptes d''écarts de convesion passif'),
  ('01171', 'Réouverture des comptes d''écarts sur créances immobilisées'),
  ('01172', 'Réouverture des comptes d''écarts sur dettes de financement'),
  ('012', 'Réouverture des comptes d''actif immobilisé'),
  ('0121', 'Réouverture des comptes d''immobilisations en non-valeurs'),
  ('01211', 'Réouverture des comptes de frais préléminaires'),
  ('01212', 'Réouverture des comptes de charges à répartir sur plusieurs exercices'),
  ('01213', 'Réouverture des comptes de primes de remboursement des obligations'),
  ('0122', 'Réouverture des comptes d''immobilisations incorporelles'),
  ('01221', 'Réouverture des comptes de d''immobilisations en recherche et développement'),
  ('01222', 'Réouverture des comptes de brevets, marques, droits et valeurs similaires'),
  ('01223', 'Réouverture des comptes de fonds commercial'),
  ('01228', 'Réouverture des comptes d''autres immobilisations incorporelles'),
  ('0123', 'Réouverture des comptes des immobilisations corporelles'),
  ('01231', 'Réouverture des comptes de terrains'),
  ('01232', 'Réouverture des comptes de constructions'),
  ('01233', 'Réouverture des comptes des installations techniques, matériel et outillage'),
  ('01234', 'Réouverture des comptes de matériel de transport'),
  (')1235', 'Réouverture des comptes de mobilier, matériel du bureau et aménagements'),
  ('01238', 'Réouverture des comptes des autres immobilisations corporelles'),
  ('01239', 'Réouverture des comptes des immobilisations corporelles en cours'),
  ('0124', 'Réouverture des comptes des immobilisations financières'),
  ('0125', 'Réouverture des comptes des immobilisations financières'),
  ('01241', 'Réouverture des comptes de prets immobilisés'),
  ('01248', 'Réouverture des comptes des autres créances financières'),
  ('01251', 'Réouverture des comptes de titres de participation'),
  ('01258', 'Réouverture des comptes des autres titres immobilisés'),
  ('0127', 'Réouverture des comptes des écarts de conversion - actif'),
  ('01271', 'Réouverture des comptes des écarts sur créances immobilisées'),
  ('01272', 'Réouverture des comptes des écarts sur dettes de financement'),
  ('0128', 'Réouverture des comptes des amortissements des immobilisations'),
  ('0129', 'Réouverture des comptes de provisions pour dépréciation des comptes de l''actif immobilisé'),
  ('013', 'Réouverture des comptes d''actif circulant (hors trésorerie)'),
  ('0131', 'Réouverture des comptes de stocks'),
  ('01311', 'Réouverture des comptes de marchandises'),
  ('01312', 'Réouverture des comptes de matières et fournitures consommables'),
  ('01313', 'Réouverture des comptes de produits en cours'),
  ('01314', 'Réouverture des comptes de produits intérmédiaires et produits résiduels'),
  ('01315', 'Réouverture des comptes de produits finis'),
  ('0134', 'Réouverture des comptes de créances'),
  ('01341', 'Réouverture des comptes de fournisseurs débiteurs, avances et acomptes'),
  ('01342', 'Réouverture des comptes de clients et comptes rattachés'),
  ('01343', 'Réouverture des comptes de personnel débiteur'),
  ('01345', 'Réouverture des comptes d''Etat débiteur'),
  ('01346', 'Réouverture des comptes d''associés débiteurs'),
  ('01348', 'Réouverture des comptes des autres débiteurs'),
  ('01349', 'Réouverture des comptes de régularisation - actif'),
  ('0135', 'Réouverture des comptes, titres et valeurs de placement'),
  ('0137', 'Réouverture des comptes des écarts de conversion - actif (éléments circulants)'),
  ('0139', 'Réouverture des comptes de provisions pour dépréciation des comptes de l''actif circulant'),
  ('014', 'Réouverture des comptes de passif circulant (hors trésorerie)'),
  ('0144', 'Réouverture des comptes de dettes du passif circulant'),
  ('01441', 'Réouverture des comptes de fournisseurs et comptes rattachés'),
  ('01442', 'Réouverture des comptes de clients créditeurs, avances èet acomptes'),
  ('01443', 'Réouverture des comptes du personnel - créditeur'),
  ('01444', 'Réouverture des comptes des organismes sociaux créditeurs'),
  ('01445', 'Réouverture des comptes des comptes Etat - créditeur'),
  ('01446', 'Réouverture des comptes d''associés créditeur'),
  ('01448', 'Réouverture des comptes des autres créanciers'),
  ('01449', 'Réouverture des comptes de régularisation - passif'),
  ('0145', 'Réouverture des comptes des autres provisions pour risques et charges'),
  ('0147', 'Réouverture des comptes des écarts de conversion - passif (éléments circulants)'),
  ('015', 'Réouverture des comptes de trésorerie'),
  ('0151', 'Réouverture des comptes de trésorerie - actif'),
  ('01511', 'Réouverture des comptes de chèques et valeurs à encaisser'),
  ('01514', 'Réouverture des comptes de banques, TG et CP (soldes débiteurs)'),
  ('01516', 'Réouverture des comptes de caisses, régies d''avances et accréditifs'),
  ('0155', 'Réouverture des comptes de trésorerie - passif'),
  ('01552', 'Réouverture des crédits d''escompte'),
  ('01553', 'Réouverture des comptes de crédits de trésorerie'),
  ('01554', 'Réouverture des comptes de banques (soldes créditeurs)'),
  ('0159', 'Réouverture des comptes de provisions pour dépréciation des comptes de trésorerie'),
  ('02', 'Cloture du bilan'),
  ('021', 'Cloture des comptes de financement personnel'),
  ('0211', 'Cloture des comptes de capitaux propres'),
  ('02111', 'Cloture des comptes de capital social ou permanent'),
  ('02112', 'Cloture des comptes des primes d''émission, de fusion, d''apport'),
  ('02113', 'Cloture des comptes des écarts de réévaluation'),
  ('02114', 'Cloture des comptes de résérve légale'),
  ('02115', 'Cloture des comptes des autres réserves'),
  ('02116', 'Cloture des comptes du report à nouveau'),
  ('02118', 'Cloture des comptes des résultats nets en instance d''affectation'),
  ('02119', 'Cloture des comptes du résultat net de l''exercice'),
  ('0213', 'Cloture des comptes de capitaux propres assimilés'),
  ('02131', 'Cloture des comptes de subventions d''investissement'),
  ('02135', 'Cloture des comptes de provisions réglementées'),
  ('0214', 'Cloture des comptes des dettes de financement'),
  ('02141', 'Cloture des comptes d''emprunts obligataires'),
  ('02148', 'Cloture des comptes des autres dettes de financeemnt'),
  ('0215', 'Cloture des comptes de provisions durables pour risques et charges'),
  ('02151', 'Cloture des comptes de provisions pour risques'),
  ('02155', 'Cloture des comptes de provisions pour charges'),
  ('0216', 'Cloture des comptes de liaison des établissements et succursales'),
  ('0217', 'Cloture des comptes d''écarts de convesion passif'),
  ('02171', 'Cloture des comptes d''écarts sur créances immobilisées'),
  ('02172', 'Cloture des comptes d''écarts sur dettes de financement'),
  ('022', 'Cloture des comptes d''actif immobilisé'),
  ('0221', 'Cloture des comptes d''immobilisations en non-valeurs'),
  ('02211', 'Cloture des comptes de frais préléminaires'),
  ('02212', 'Cloture des comptes de charges à répartir sur plusieurs exercices'),
  ('02213', 'Cloture des comptes de primes de remboursement des obligations'),
  ('0222', 'Cloture des comptes des immobilisations incorporelles'),
  ('02221', 'Cloture des comptes de d''immobilisations en recherche et développement'),
  ('02222', 'Cloture des comptes de brevets, marques, droits et valeurs similaires'),
  ('02223', 'Cloture des comptes de fonds commercial'),
  ('02228', 'Cloture des comptes des autres immobilisations incorporelles'),
  ('0223', 'Cloture des comptes des immobilisations corporelles'),
  ('02231', 'Cloture des comptes de terrains'),
  ('02232', 'Cloture des comptes de constructions'),
  ('02233', 'Cloture des comptes des installations techniques, matériel et outillage'),
  ('02234', 'Cloture des comptes de matériel de transport'),
  ('02235', 'Cloture des comptes de mobilier, matériel du bureau et aménagements'),
  ('02238', 'Cloture des comptes des autres immobilisations corporelles'),
  ('02239', 'Cloture des comptes des immobilisations corporelles en cours'),
  ('0224', 'Cloture des comptes des immobilisations financières'),
  ('0225', 'Cloture des comptes des immobilisations financières'),
  ('02241', 'Cloture des comptes de prets immobilisés'),
  ('02248', 'Cloture des comptes des autres créances financières'),
  ('02251', 'Cloture des comptes de titres de participation'),
  ('02258', 'Cloture des comptes des autres titres immobilisés'),
  ('0227', 'Cloture des comptes des écarts de conversion - actif'),
  ('02271', 'Cloture des comptes des écarts sur créances immobilisées'),
  ('02272', 'Cloture des comptes des écarts sur dettes de financement'),
  ('0228', 'Cloture des comptes des amortissements des immobilisations'),
  ('0229', 'Cloture des comptes de provisions pour dépréciation des comptes de l''actif immobilisé'),
  ('023', 'Cloture des comptes d''actif circulant (hors trésorerie)'),
  ('0231', 'Cloture des comptes de stocks'),
  ('02311', 'Cloture des comptes de marchandises'),
  ('02312', 'Cloture des comptes de matières et fournitures consommables'),
  ('02313', 'Cloture des comptes de produits en cours'),
  ('02314', 'Cloture des comptes de produits intérmédiaires et produits résiduels'),
  ('02315', 'Cloture des comptes de produits finis'),
  ('0234', 'Cloture des comptes de créances'),
  ('02341', 'Cloture des comptes de fournisseurs débiteurs, avances et acomptes'),
  ('02342', 'Cloture des comptes de clients et comptes rattachés'),
  ('02343', 'Cloture des comptes de personnel débiteur'),
  ('02345', 'Cloture des comptes d''Etat débiteur'),
  ('02346', 'Cloture des comptes d''associés débiteurs'),
  ('02348', 'Cloture des comptes des autres débiteurs'),
  ('02349', 'Cloture des comptes de régularisation - actif'),
  ('0235', 'Cloture des comptes, titres et valeurs de placement'),
  ('0237', 'Cloture des comptes des écarts de conversion - actif (éléments circulants)'),
  ('0239', 'Cloture des comptes de provisions pour dépréciation des comptes de l''actif circulant'),
  ('024', 'Cloture des comptes de passif circulant (hors trésorerie)'),
  ('0244', 'Cloture des comptes de dettes du passif circulant'),
  ('02441', 'Cloture des comptes de fournisseurs et comptes rattachés'),
  ('02442', 'Cloture des comptes de clients créditeurs, avances èet acomptes'),
  ('02443', 'Cloture des comptes du personnel - créditeur'),
  ('02444', 'Cloture des comptes des organismes sociaux créditeurs'),
  ('02445', 'Cloture des comptes des comptes Etat - créditeur'),
  ('02446', 'Cloture des comptes d''associés créditeurs'),
  ('02448', 'Cloture des comptes des autres créanciers'),
  ('02449', 'Cloture des comptes de régularisation - passif'),
  ('0245', 'Cloture des comptes des autres provisions pour risques et charges'),
  ('0247', 'Cloture des comptes des écarts de conversion - passif (éléments circulants)'),
  ('025', 'Cloture des comptes de trésorerie'),
  ('0251', 'Cloture des comptes de trésorerie - actif'),
  ('02511', 'Cloture des comptes de chèques et valeurs à encaisser'),
  ('02514', 'Cloture des comptes de banques, TG et CP (soldes débiteurs)'),
  ('02516', 'Cloture des comptes de caisses, régies d''avances et accréditifs'),
  ('0255', 'Cloture des comptes de trésorerie - passif'),
  ('02552', 'Cloture des crédits d''escompte'),
  ('02553', 'Cloture des comptes de crédits de trésorerie'),
  ('0259', 'Cloture des comptes de provisions pour dépréciation des comptes de trésorerie'),
  ('03', 'Comptes d''ordre'),
  ('031', 'Opération en instance de dénouément (débit)'),
  ('0311', 'Opération de débit en instance de dénouément'),
  ('0319', 'Contrepartie des opérations en instance d''affectation'),
  ('033', 'Opération en instance de dénouément (crédit)'),
  ('0331', 'Opération de crédit en instance de dénouément'),
  ('0339', 'Contrepartie des opérations en instance de dénouément'),
  ('035', 'Opération en devises entrées'),
  ('0351', 'Contre - valeur devise - entrées'),
  ('0359', 'Contrepartie - devises - entrées'),
  ('036', 'Opération en devises - sortie'),
  ('0361', 'Contre - valeur devise - sorties'),
  ('0369', 'Contrepartie - devises - sorties'),
  ('038', 'Autres doonées statistiques'),
  ('0381', 'Opérations statistiques suivies'),
  ('0389', 'Contrepartie des opérations statistiques suivies'),
  ('04', 'Engagements donnés'),
  ('041', 'Avals, cautions et garanties donnés'),
  ('0411', 'Avals, cautions et garanties donnés'),
  ('0419', 'Débiteurs pour avals et cautions donnés'),
  ('043', 'Engagements en matière de pensions de retraite et obligations similaires'),
  ('0431', 'Engagements en matière de pensions de retraite et obligations similaires'),
  ('0439', 'Débiteurs pour engagements en matière de pensions de retraite et obligations similaires'),
  ('045', 'Effets circulants sous l''endos de l''entreprise'),
  ('0451', 'Effets circulants sous l''endos de l''entreprise'),
  ('0459', 'Débiteurs pour effets circulants sous l''endos de l''entreprise'),
  ('046', 'Engagements donnés pour pour prets consentis'),
  ('0461', 'Prets consentis non encore versés'),
  ('0469', 'Débiteurs pour prets consentis non encore versés'),
  ('048', 'Autres engagements donnés'),
  ('0481', 'Autres engagements donnés'),
  ('0489', 'Débiteurs pour autres engagements donnés'),
  ('05', 'Engagements reçus'),
  ('051', 'Avals, cautions et garanties reçus'),
  ('0511', 'Avals, cautions et garanties reçus'),
  ('0519', 'Créditeurs pour avals, cautions et garanties reçus'),
  ('055', 'Biens détenus en garantie par l''entreprise'),
  ('0551', 'Biens détenus en garantie par l''entreprise'),
  ('0559', 'Créditeurs pour biens détenus en garantie par l''entreprise'),
  ('056', 'Engagements reçus sur dettes de financement'),
  ('0561', 'Emrunts non encore encaissés'),
  ('0569', 'Créditeurs pour engagements non encore encaissés'),
  ('057', 'Engagements reçus sur sur trésorerie'),
  ('0571', 'Montant non utilisé des découverts autorisés'),
  ('0572', 'Plafond d''escomptes non utilisé'),
  ('0579', 'Créditeurs pour engagements reçus sur trésorerie'),
  ('058', 'Autres engagements reçus'),
  ('0581', 'Autres engagements reçus'),
  ('0589', 'Créditeurs pour autres engagements reçus'),
  ('06', 'Engagements sur opérations de crédit-bail'),
  ('061', 'Redevances de crédit-bail restant à courir'),
  ('0611', 'Redevances de crédit-bail restant à courir'),
  ('0619', 'Debiteurs pour redevances de crédit-bail restant à courir'),
  ('065', 'Engagements reçus pour utilisation en crédit-bail'),
  ('0651', 'Engagements reçus pour utilisation en crédit-bail'),
  ('0659', 'Créditeurs pour engagements reçus pour utilisation en crédit-bail'),
  ('08', 'Autres comptes spéciaux'),
  ('081', 'Autres comptes spéciaux'),
  ('0811', 'Autres comptes spéciaux'),
  ('0819', 'Contrepartie des autres comptes spéciaux');
